#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
BIN_DIR="$PREFIX/bin"
CONFIG_DIR="${FASRC_CONFIG_DIR:-$HOME/.config/fasrc}"
SSH_CONFIG="${FASRC_SSH_CONFIG:-$HOME/.ssh/config}"
SSH_INCLUDE="${FASRC_SSH_INCLUDE_FILE:-$HOME/.ssh/fasrc_compute_config}"
FASRC_HOST="${FASRC_HOST:-login.rc.fas.harvard.edu}"
FASRC_ALIAS="${FASRC_ALIAS:-fasrc}"
FASRC_USER="${FASRC_USER:-}"

require_safe_token() {
  local name="$1"
  local value="$2"

  [[ "$value" =~ ^[A-Za-z0-9._-]+$ ]] || {
    printf '%s must contain only letters, digits, dots, underscores, or hyphens.\n' "$name" >&2
    exit 1
  }
}

usage() {
  cat <<'EOF'
Usage:
  ./install.sh [--user FASRC_USER] [--host LOGIN_HOST]

Environment:
  PREFIX=/path              Install prefix. Default: ~/.local
  FASRC_CONFIG_DIR=/path    Config directory. Default: ~/.config/fasrc
  FASRC_ALIAS=name          SSH login alias. Default: fasrc
  FASRC_HOST=host           FASRC login host. Default: login.rc.fas.harvard.edu
EOF
}

while (($#)); do
  case "$1" in
    --user)
      [[ $# -ge 2 ]] || { printf 'Missing value for --user\n' >&2; exit 1; }
      FASRC_USER="$2"
      shift 2
      ;;
    --host)
      [[ $# -ge 2 ]] || { printf 'Missing value for --host\n' >&2; exit 1; }
      FASRC_HOST="$2"
      shift 2
      ;;
    -h|--help|help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$FASRC_USER" ]]; then
  if [[ -t 0 ]]; then
    default_user="$(whoami)"
    printf 'FASRC username [%s]: ' "$default_user"
    read -r FASRC_USER
    FASRC_USER="${FASRC_USER:-$default_user}"
  else
    FASRC_USER="$(whoami)"
  fi
fi

if [[ "$(uname -s)" != "Darwin" && "${FASRC_ALLOW_UNSUPPORTED_PLATFORM:-0}" != "1" ]]; then
  printf '%s\n' 'This utility supports macOS Remote-SSH compute-node sessions. FASRC documents Remote SSH to compute nodes as macOS-only; use the FASRC Remote Tunnel workflow on Windows or set FASRC_ALLOW_UNSUPPORTED_PLATFORM=1 only if you understand the limitation.' >&2
  exit 1
fi

require_safe_token "FASRC username" "$FASRC_USER"
require_safe_token "FASRC host" "$FASRC_HOST"
require_safe_token "FASRC alias" "$FASRC_ALIAS"

mkdir -p "$BIN_DIR" "$CONFIG_DIR" "$HOME/.ssh" "$HOME/.ssh/sockets"
chmod 700 "$HOME/.ssh" "$HOME/.ssh/sockets"

rm -f "$BIN_DIR/fasrc" "$BIN_DIR/fasrc-code" "$BIN_DIR/fasrc-code-proxy"
rm -rf "$HOME/.local/state/fasrc-code"
install -m 755 "$ROOT_DIR/bin/fasrc" "$BIN_DIR/fasrc"
install -m 755 "$ROOT_DIR/bin/fasrc-proxy" "$BIN_DIR/fasrc-proxy"

if [[ ! -f "$CONFIG_DIR/extensions.txt" ]]; then
  install -m 644 "$ROOT_DIR/config/extensions.txt" "$CONFIG_DIR/extensions.txt"
else
  while IFS= read -r ext; do
    [[ -n "$ext" && "$ext" != \#* ]] || continue
    if ! grep -ixF "$ext" "$CONFIG_DIR/extensions.txt" >/dev/null; then
      printf '%s\n' "$ext" >>"$CONFIG_DIR/extensions.txt"
    fi
  done <"$ROOT_DIR/config/extensions.txt"
fi

touch "$SSH_CONFIG"
chmod 600 "$SSH_CONFIG"

include_line="Include $SSH_INCLUDE"
if ! grep -qxF "$include_line" "$SSH_CONFIG"; then
  tmp_file="$(mktemp)"
  {
    printf '%s\n\n' "$include_line"
    cat "$SSH_CONFIG"
  } >"$tmp_file"
  mv "$tmp_file" "$SSH_CONFIG"
  chmod 600 "$SSH_CONFIG"
fi

if [[ ! -f "$SSH_INCLUDE" ]]; then
  cat >"$SSH_INCLUDE" <<EOF
# Auto-generated by \`fasrc\`.
# Active compute-node aliases are written here.

Host fasrc-compute
  HostName fasrc-compute
  User $FASRC_USER
  ProxyCommand $BIN_DIR/fasrc-proxy
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes
  ServerAliveInterval 60
  ServerAliveCountMax 3
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  CheckHostIP no
EOF
else
  tmp_file="$(mktemp)"
  awk -v proxy="$BIN_DIR/fasrc-proxy" '
    /^[[:space:]]*Host[[:space:]]+/ {
      in_generic = 0
      for (i = 2; i <= NF; i++) {
        if ($i == "fasrc-compute") {
          in_generic = 1
        }
      }
    }

    in_generic && tolower($1) == "proxycommand" {
      print "  ProxyCommand " proxy
      next
    }

    { print }
  ' "$SSH_INCLUDE" >"$tmp_file"
  mv "$tmp_file" "$SSH_INCLUDE"
fi
chmod 600 "$SSH_INCLUDE"

if ! awk -v alias="$FASRC_ALIAS" '
  tolower($1) == "host" {
    for (i = 2; i <= NF; i++) {
      if ($i == alias) {
        found = 1
      }
    }
  }
  END {
    exit(found ? 0 : 1)
  }
' "$SSH_CONFIG"; then
  cat >>"$SSH_CONFIG" <<EOF

Host $FASRC_ALIAS
  HostName $FASRC_HOST
  User $FASRC_USER
  IgnoreUnknown UseKeychain
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
  ControlMaster auto
  ControlPath ~/.ssh/sockets/%r@%h-%p
  ControlPersist 96h
  ServerAliveInterval 60
  ServerAliveCountMax 3
EOF
fi

tmp_file="$(mktemp)"
awk -v alias="$FASRC_ALIAS" '
  function finish_host() {
    if (in_target && !saw_controlpersist) {
      print "  ControlPersist 96h"
    }
  }

  /^[[:space:]]*Host[[:space:]]+/ {
    finish_host()
    in_target = 0
    saw_controlpersist = 0
    for (i = 2; i <= NF; i++) {
      if ($i == alias) {
        in_target = 1
      }
    }
  }

  in_target && tolower($1) == "controlpersist" {
    print "  ControlPersist 96h"
    saw_controlpersist = 1
    next
  }

  { print }

  END {
    finish_host()
  }
' "$SSH_CONFIG" >"$tmp_file"
mv "$tmp_file" "$SSH_CONFIG"
chmod 600 "$SSH_CONFIG"

if [[ ! -f "$HOME/.ssh/id_ed25519" ]]; then
  ssh-keygen -t ed25519 -N '' -f "$HOME/.ssh/id_ed25519" >/dev/null
fi

if [[ "$BIN_DIR" == "$HOME/.local/bin" ]]; then
  path_line='export PATH="$HOME/.local/bin:$PATH"'
else
  path_line="export PATH=\"$BIN_DIR:\$PATH\""
fi
case "${SHELL:-}" in
  */zsh)
    rc_file="${ZDOTDIR:-$HOME}/.zshrc"
    ;;
  */bash)
    rc_file="$HOME/.bashrc"
    ;;
  *)
    rc_file="$HOME/.profile"
    ;;
esac

touch "$rc_file"
tmp_rc="$(mktemp)"
awk '
  $0 == "alias fasrc-workspace='\''fasrc'\''" { next }
  $0 == "alias fasrc-workspace='\''fasrc-code'\''" { next }
  { print }
' "$rc_file" >"$tmp_rc"
mv "$tmp_rc" "$rc_file"
if ! grep -qxF "$path_line" "$rc_file"; then
  printf '\n%s\n' "$path_line" >>"$rc_file"
fi

"$BIN_DIR/fasrc" help >/dev/null

cat <<EOF
Installed fasrc workflow.

Command:
  $BIN_DIR/fasrc

Config:
  $CONFIG_DIR/extensions.txt
  $SSH_CONFIG

Next:
  Open a new terminal or run: export PATH="$BIN_DIR:\$PATH"
  Then run: fasrc setup
EOF
