#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${PREFIX:-$HOME/.local}"
BIN_DIR="$PREFIX/bin"
CONFIG_DIR="${FASRC_CONFIG_DIR:-$HOME/.config/fasrc}"
LOGIN_ALIAS_FILE="$CONFIG_DIR/login-alias"
SSH_CONFIG="${FASRC_SSH_CONFIG:-$HOME/.ssh/config}"
SSH_INCLUDE="${FASRC_SSH_INCLUDE_FILE:-$HOME/.ssh/fasrc_compute_config}"
FASRC_HOST="${FASRC_HOST:-login.rc.fas.harvard.edu}"
FASRC_ALIAS="${FASRC_ALIAS:-fasrc}"
FASRC_USER="${FASRC_USER:-}"

require_safe_token() {
  local name="$1"
  local value="$2"

  [[ "$value" =~ ^[A-Za-z0-9._-]+$ ]] || {
    printf '%s must contain only letters, digits, dots, underscores, or hyphens.\n' "$name" >&2
    exit 1
  }
}

usage() {
  cat <<'EOF'
Usage:
  ./install.sh [--user FASRC_USER] [--host LOGIN_HOST]

Environment:
  PREFIX=/path              Install prefix. Default: ~/.local
  FASRC_CONFIG_DIR=/path    Config directory. Default: ~/.config/fasrc
  FASRC_ALIAS=name          SSH login alias. Default: fasrc
  FASRC_HOST=host           FASRC login host. Default: login.rc.fas.harvard.edu
EOF
}

while (($#)); do
  case "$1" in
    --user)
      [[ $# -ge 2 ]] || { printf 'Missing value for --user\n' >&2; exit 1; }
      FASRC_USER="$2"
      shift 2
      ;;
    --host)
      [[ $# -ge 2 ]] || { printf 'Missing value for --host\n' >&2; exit 1; }
      FASRC_HOST="$2"
      shift 2
      ;;
    -h|--help|help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$FASRC_USER" ]]; then
  if [[ -t 0 ]]; then
    default_user="$(whoami)"
    printf 'FASRC username [%s]: ' "$default_user"
    read -r FASRC_USER
    FASRC_USER="${FASRC_USER:-$default_user}"
  else
    FASRC_USER="$(whoami)"
  fi
fi

if [[ "$(uname -s)" != "Darwin" && "${FASRC_ALLOW_UNSUPPORTED_PLATFORM:-0}" != "1" ]]; then
  printf '%s\n' 'This utility supports macOS Remote-SSH compute-node sessions. FASRC documents Remote SSH to compute nodes as macOS-only; use the FASRC Remote Tunnel workflow on Windows or set FASRC_ALLOW_UNSUPPORTED_PLATFORM=1 only if you understand the limitation.' >&2
  exit 1
fi

require_safe_token "FASRC username" "$FASRC_USER"
require_safe_token "FASRC host" "$FASRC_HOST"
require_safe_token "FASRC alias" "$FASRC_ALIAS"

missing_commands=()
for required_command in ssh ssh-keygen awk perl base64 jq code readlink; do
  if ! command -v "$required_command" >/dev/null 2>&1; then
    missing_commands+=("$required_command")
  fi
done
if [[ "${#missing_commands[@]}" -gt 0 ]]; then
  printf 'Missing required command(s): %s\n' "${missing_commands[*]}" >&2
  printf '%s\n' 'Install VS Code and its `code` shell command, plus jq, before running this installer.' >&2
  exit 1
fi

mkdir -p "$BIN_DIR" "$CONFIG_DIR" "$HOME/.ssh" "$HOME/.ssh/sockets"
chmod 700 "$CONFIG_DIR" "$HOME/.ssh" "$HOME/.ssh/sockets"

printf '%s\n' "$FASRC_ALIAS" >"$LOGIN_ALIAS_FILE"
chmod 600 "$LOGIN_ALIAS_FILE"

rm -f "$BIN_DIR/fasrc" "$BIN_DIR/fasrc-proxy" "$BIN_DIR/fasrc-code" "$BIN_DIR/fasrc-code-proxy"
rm -rf "$HOME/.local/state/fasrc-code"
install -m 755 "$ROOT_DIR/bin/fasrc" "$BIN_DIR/fasrc"

if [[ ! -f "$CONFIG_DIR/extensions.txt" ]]; then
  install -m 600 "$ROOT_DIR/config/extensions.txt" "$CONFIG_DIR/extensions.txt"
else
  while IFS= read -r ext; do
    [[ -n "$ext" && "$ext" != \#* ]] || continue
    if ! grep -ixF "$ext" "$CONFIG_DIR/extensions.txt" >/dev/null; then
      printf '%s\n' "$ext" >>"$CONFIG_DIR/extensions.txt"
    fi
  done <"$ROOT_DIR/config/extensions.txt"
fi
chmod 600 "$CONFIG_DIR/extensions.txt"
for personal_config in "$CONFIG_DIR/defaults.env" "$CONFIG_DIR/paths.env"; do
  [[ ! -f "$personal_config" ]] || chmod 600 "$personal_config"
done

touch "$SSH_CONFIG"
chmod 600 "$SSH_CONFIG"

if [[ ! -f "$SSH_INCLUDE" ]]; then
  cat >"$SSH_INCLUDE" <<'EOF'
# Auto-generated by `fasrc`.
# Active compute-node aliases are written here.
EOF
else
  tmp_file="$(mktemp)"
  awk '
    /^[[:space:]]*Host[[:space:]]+/ {
      skip_generic = (NF == 2 && $2 == "fasrc-compute")
    }
    skip_generic { next }
    { print }
  ' "$SSH_INCLUDE" >"$tmp_file"
  mv "$tmp_file" "$SSH_INCLUDE"
fi
chmod 600 "$SSH_INCLUDE"

managed_begin="# BEGIN fasrc-vscode managed login"
managed_end="# END fasrc-vscode managed login"
tmp_file="$(mktemp)"
{
  cat <<EOF
$managed_begin
Host $FASRC_ALIAS
  HostName $FASRC_HOST
  User $FASRC_USER
  IgnoreUnknown UseKeychain
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
  ControlMaster auto
  ControlPath ~/.ssh/sockets/%r@%h-%p
  ControlPersist 96h
  ServerAliveInterval 60
  ServerAliveCountMax 3
$managed_end

Include "$SSH_INCLUDE"

EOF
  awk \
    -v managed_begin="$managed_begin" \
    -v managed_end="$managed_end" \
    -v include_path="$SSH_INCLUDE" \
    -v home_dir="$HOME" \
    -v ssh_dir="$HOME/.ssh" '
      function trim(value) {
        sub(/^[[:space:]]+/, "", value)
        sub(/[[:space:]]+$/, "", value)
        return value
      }

      function canonical_include(value, first, last) {
        value = trim(value)
        first = substr(value, 1, 1)
        last = substr(value, length(value), 1)
        if ((first == "\"" && last == "\"") || (first == "'" && last == "'")) {
          value = substr(value, 2, length(value) - 2)
        }
        if (value == "~") {
          return home_dir
        }
        if (substr(value, 1, 2) == "~/") {
          return home_dir "/" substr(value, 3)
        }
        if (value == "$HOME") {
          return home_dir
        }
        if (substr(value, 1, 6) == "$HOME/") {
          return home_dir "/" substr(value, 7)
        }
        if (substr(value, 1, 1) != "/") {
          return ssh_dir "/" value
        }
        return value
      }

      $0 == managed_begin { in_managed = 1; next }
      $0 == managed_end { in_managed = 0; next }
      in_managed { next }

      tolower($1) == "include" {
        line = $0
        sub(/^[[:space:]]*[Ii][Nn][Cc][Ll][Uu][Dd][Ee][[:space:]]+/, "", line)
        sub(/[[:space:]]+#[^\n]*$/, "", line)
        if (canonical_include(line) == canonical_include(include_path)) {
          next
        }
      }

      { print }
    ' "$SSH_CONFIG"
} >"$tmp_file"
mv "$tmp_file" "$SSH_CONFIG"
chmod 600 "$SSH_CONFIG"

if [[ ! -f "$HOME/.ssh/id_ed25519" ]]; then
  ssh-keygen -t ed25519 -N '' -f "$HOME/.ssh/id_ed25519" >/dev/null
fi

if [[ "$BIN_DIR" == "$HOME/.local/bin" ]]; then
  path_line='export PATH="$HOME/.local/bin:$PATH"'
else
  path_line="export PATH=\"$BIN_DIR:\$PATH\""
fi
case "${SHELL:-}" in
  */zsh)
    rc_file="${ZDOTDIR:-$HOME}/.zshrc"
    ;;
  */bash)
    rc_file="$HOME/.bashrc"
    ;;
  *)
    rc_file="$HOME/.profile"
    ;;
esac

rc_update_file="$rc_file"
if [[ -L "$rc_file" ]]; then
  rc_link_target="$(readlink "$rc_file")"
  case "$rc_link_target" in
    /*) rc_update_file="$rc_link_target" ;;
    *) rc_update_file="$(dirname "$rc_file")/$rc_link_target" ;;
  esac
fi

touch "$rc_update_file"
tmp_rc="$(mktemp "${rc_update_file}.fasrc.XXXXXX")"
cp -p "$rc_update_file" "$tmp_rc"
awk '
  $0 == "alias fasrc-workspace='\''fasrc'\''" { next }
  $0 == "alias fasrc-workspace='\''fasrc-code'\''" { next }
  { print }
' "$rc_update_file" >"$tmp_rc"
mv "$tmp_rc" "$rc_update_file"
if ! grep -qxF "$path_line" "$rc_update_file"; then
  printf '\n%s\n' "$path_line" >>"$rc_update_file"
fi

"$BIN_DIR/fasrc" help >/dev/null

cat <<EOF
Installed fasrc workflow.

Command:
  $BIN_DIR/fasrc

Config:
  $CONFIG_DIR/extensions.txt
  $LOGIN_ALIAS_FILE
  $SSH_CONFIG

Next:
  Open a new terminal or run: export PATH="$BIN_DIR:\$PATH"
  Then run: fasrc setup
EOF
